### ISSUE TITLE
Create branding and logo

### ISSUE THREAD

**Issue by ecurrencyhodler** [ecurrencyhodler/Bitcoin-PAL#3]
The name of our project will be the crowd-sourced data submission platform. But we must still choose a loose name for the bitcoin education chatbot.

**Tasks**

- [x] Choose name for bitcoin education chatbot
- [x] Choose name for new data submission platform
- [x] Create banner for new data submission platform
